/*
 * This file is generated by jOOQ.
 */
package pl.subtelny.core;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import pl.subtelny.core.tables.Users;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index USERS_UUID_KEY = Indexes0.USERS_UUID_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_UUID_KEY = Internal.createIndex("users_uuid_key", Users.USERS, new OrderField[] { Users.USERS.UUID }, true);
    }
}
