/*
 * This file is generated by jOOQ.
 */
package pl.subtelny.core;


import javax.annotation.processing.Generated;

import pl.subtelny.core.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
